# -*- coding: utf-8 -*-
"""Assingment_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kyy-MXMdRASP4Stn8yKUFn-Ni3Q9kC51
"""

import math
from scipy import stats
p = 0.2 #probability of success 
n = 5    # no of trials
X = stats.binom(n, p) # Declare X to be a binomial random variable
print("Probability at X=2")
print (X.pmf(2),"\n")          # P(X = 2)